//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public string MaBlog { get; set; }
        public string AnhBlog { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string NguoiPost { get; set; }
        public string NoiDung { get; set; }
    }
}
