//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        public int MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> TongTien { get; set; }
    }
}
