//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaChatLieu { get; set; }
        public string MauSac { get; set; }
        public string HangSX { get; set; }
        public Nullable<double> Gia { get; set; }
        public string MaDT { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
        public string Maloai { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
