//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ThongTinHoaDon
    {
        public Nullable<long> STT { get; set; }
        public string TenNguoiDung { get; set; }
        public string TenKH { get; set; }
        public int MaHD { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string Anh { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    }
}
